// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3xns6smY5s1KsALXMY4FHI3EjdsXUN9M',
    appId: '1:309441478036:web:4674a21a25132611076381',
    messagingSenderId: '309441478036',
    projectId: 'chat-app-7afe0',
    authDomain: 'chat-app-7afe0.firebaseapp.com',
    storageBucket: 'chat-app-7afe0.appspot.com',
    measurementId: 'G-JZJSFD5SYC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIIzoNuGZuw2nJWSuR96zMhXiLse1QrDg',
    appId: '1:309441478036:android:309163f6268166ba076381',
    messagingSenderId: '309441478036',
    projectId: 'chat-app-7afe0',
    storageBucket: 'chat-app-7afe0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI_WVQy_zH1jYSCNpUMGxOh_UdvmuxIqM',
    appId: '1:309441478036:ios:53c0a55535ce29ce076381',
    messagingSenderId: '309441478036',
    projectId: 'chat-app-7afe0',
    storageBucket: 'chat-app-7afe0.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI_WVQy_zH1jYSCNpUMGxOh_UdvmuxIqM',
    appId: '1:309441478036:ios:29f9a4d980ca686d076381',
    messagingSenderId: '309441478036',
    projectId: 'chat-app-7afe0',
    storageBucket: 'chat-app-7afe0.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
